### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by imanaspaul** [macropin/django-registration#356] opened 2019-02-24 17:54 UTC
File "C:\Users\MANASH\AppData\Local\Programs\Python\Python36\lib\site-packages\registration\models.py", line 189, in RegistrationProfile
    user = models.OneToOneField(UserModelString(), verbose_name=_('user'))
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by joshblum** [comment] 2019-02-25 04:19
@imanaspaul what version of the library are you running? is this a duplicate of https://github.com/macropin/django-registration/issues/336 ?

**Comment by macropin** [comment] 2019-12-03 01:28
Closing for now. Please feel free to reopen with more information.

**Closed by macropin** 2019-12-03 01:28 UTC
