### ISSUE TITLE
WARNINGS: registration.RegistrationProfile.user

### ISSUE THREAD

**Issue by painhardcore** [macropin/django-registration#44] opened 2015-04-24 23:07 UTC
Getting this warning
"Performing system checks...
System check identified some issues:

WARNINGS:
registration.RegistrationProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 1 issue (0 silenced).
"
Django 1.8. python3.4 postgres 9.4

What's wrong with schema?

**Comment by TaqiOfficial** [comment] 2015-04-25 23:04
I have the same issue with `django 1.8` and `postgres 9.4`. Address the issue ASAP.

**Comment by twcook** [comment] 2015-04-30 09:04
For Django 1.8 (and future) support there is also the app_label issue.

/lib/python3.4/site-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

**Comment by martey** [comment] 2015-05-06 19:35
The original issue described here seems to be a duplicate of #42.

Since the `app_label` issue that twcook describes in happening in `django.contrib.sites`, I don't think it's applicable for this package.

**Comment by macropin** [comment] 2015-05-11 05:04
Thanks @martey . Closing.

**Closed by macropin** 2015-05-11 05:04 UTC
