### ISSUE TITLE
RequestSite issue in admin.py and default/views.py

### ISSUE THREAD

**Issue by nnamdiee** [macropin/django-registration#132] opened 2015-12-07 17:42 UTC
Just a heads up - (if not already fixed) but RequestSite is no longer in django.contrib.sites.models but is in django.contrib.sites.requests. I found that when I installed django-registration-redux, those old import statements are still there and I had to change them. If they are not changed, django throws import errors.

Thanks,
@nnamdiee

**Comment by dicato** [comment] 2015-12-07 18:13
Thanks! This is fixed in master via this commit: https://github.com/macropin/django-registration/commit/7fa127f6e6669c0e8552954487f7bf884ddc44ef

**Comment by nnamdiee** [comment] 2015-12-07 18:23
Great, thanks!

**Comment by bmeyer71** [comment] 2015-12-07 18:48
I'm not seeing those changes when viewing that file on the master branch either in my local copy or viewing it on GitHub.

**Comment by dicato** [comment] 2015-12-07 19:50
@bmeyer71 good catch! Reopening the issue.  @nnamdiee or @bmeyer71 please open a pull request with the fix if possible!

**Comment by bmeyer71** [comment] 2015-12-07 21:32
@dicato You do have the fix in the commit you posted above as far as I can tell. The issue is that @jamesturk removed those as compatibility changes in commits he did on Oct. 27th. Maybe he can comment on this further.

**Comment by jamesturk** [comment] 2015-12-07 23:28
the line linked above was in the removed compat code & dropped when 1.7 was dropped, it should still be fixed on master as seen here:

https://github.com/macropin/django-registration/blob/d217ba8ee8bd06b770a94660c752ad456878aadb/registration/admin.py#L3

**Comment by bmeyer71** [comment] 2015-12-10 16:28
thanks @jamesturk 
@dicato I did some further checks on my project and this doesn't seem to be coming up any longer. I get a warning about "class django.contrib.sites.models.Site" and not in INSTALLED_APPS etc. and will be removed in Django 1.9, but I will look at that further as it is separate from this. Unless @nnamdiee is still having trouble, it looks like this can be closed again.

**Comment by vchrisb** [comment] 2015-12-11 15:29
I'm getting the same import error.
Look at https://github.com/macropin/django-registration/blob/master/registration/admin.py#L3 as @jamesturk mentioned

**Comment by nnamdiee** [comment] 2015-12-11 18:38
I'll do a quick check just to see if I'm getting this error free. @bmeyer71

**Comment by awbacker** [comment] 2015-12-14 04:52
I don't get this in the latest (1.3a0), only in 1.2.  However, the main site still says django 1.7/8/9 compatible, which it isn't.  I'd love to stop installing this from git directly, any idea on when it will be actually released?

**Comment by macropin** [comment] 2015-12-14 05:00
@awbacker we'd be happy to accept assistance with #131

**Comment by awbacker** [comment] 2015-12-14 05:05
@macropin I looked at that and was wondering.  Is there a particular sub-issue?

**Comment by dicato** [comment] 2015-12-14 13:51
@awbacker you aren't seeing this issue when installing from the latest commit in git? If so, I'm going to close this issue :smile: #94, #113, #115 are three PRs I'd love to see merged before we create a 1.3 release.

**Comment by mcrowson** [comment] 2016-01-07 15:34
When will we see 1.3? We really need this issue addressed. The way our promotions and testing happens we need Pypi version to include this fix.

**Comment by dicato** [comment] 2016-01-07 16:01
@mcrowson hopefully soon. You can track progress and conversation in #131.

Closing this issue. It is addressed in master currently.

**Closed by dicato** 2016-01-07 16:01 UTC
