### ISSUE TITLE
Table 'test.registration_registrationprofile' doesn't exist

### ISSUE THREAD

**Issue by kazitanvirahsan** [macropin/django-registration#101] opened 2015-09-15 11:03 UTC
Request Method: 	POST
Request URL: 	..127.0.0.1:8000/accounts/register/
Django Version: 	1.8.2
Exception Type: 	ProgrammingError
Exception Value:
(1146, "Table 'test.registration_registrationprofile' doesn't exist")

happens after filling up the registration form. However I can see the new row created in auth_user table.

**Comment by dicato** [comment] 2015-09-15 13:57
Are you trying to use the example application - `test_app` - in this repository? Did you run `python manage.py migrate` before starting `runserver`?

**Comment by dicato** [comment] 2015-09-21 10:09
I believe the issue is forgetting to sync and migrate the database. Closing and will re-open if it turns out to be something else.

**Closed by dicato** 2015-09-21 10:09 UTC
