### ISSUE TITLE
'AuthUser' object has no attribute 'backend'

### ISSUE THREAD

**Issue by TaqiOfficial** [macropin/django-registration#45] opened 2015-04-25 22:10 UTC
I have customize my User model as describe in this article `http://buildthis.com/customizing-djangos-default-user-model/`. When I register new user then it successfully added to the record but after that error arises `'AuthUser' object has no attribute 'backend'`?

**Comment by AMeng** [comment] 2015-05-12 01:44
I'm not able to reproduce this. Can you provide a traceback?

**Comment by AMeng** [comment] 2015-05-17 03:40
@TaqiOfficial are you still seeing this with `django-registration-redux==1.2c1`?

**Comment by TaqiOfficial** [comment] 2015-05-17 04:34
@AMeng em' using  django-registration-redux==1.1

**Comment by AMeng** [comment] 2015-05-17 13:33
@TaqiOfficial would you mind testing with `1.2c1`?

**Comment by macropin** [comment] 2015-05-19 04:30
This is presumed fixed in v1.2.

**Closed by macropin** 2015-05-19 04:30 UTC
