### ISSUE TITLE
NoReverseMatch at /accounts/password/reset/

### ISSUE THREAD

**Issue by bmsleight** [macropin/django-registration#140] opened 2016-01-10 17:35 UTC
NoReverseMatch at /accounts/password/reset/

Reverse for 'password_reset_confirm' with arguments '()' and keyword arguments '{'token': '4BLAH-blah-BLAH5', 'uidb64': b'OA'}' not found. 0 pattern(s) tried: []

Had to follow the instruction here - 
http://stackoverflow.com/questions/23750138/django-django-registration-password-reset-error

**Comment by dicato** [comment] 2016-01-11 15:27
Could you provide your urls before and after your fix for this?

**Comment by bmsleight** [comment] 2016-01-12 20:58
Before: https://raw.githubusercontent.com/bmsleight/nonilnil/9542f01d551909392b69963573610ff700c631d4/nonilnil/urls.py

After: https://raw.githubusercontent.com/bmsleight/nonilnil/f0262259870071c18a68f54b4ec1a561a1e7eece/nonilnil/urls.py

After fixed it. 

Thanks,
Brendan

**Comment by lydiagu** [comment] 2016-03-28 15:56
I just ran into the same problem. Is there a reason that the url names in https://github.com/macropin/django-registration/blob/master/registration/auth_urls.py add a prefix of 'auth_' to the default django auth url names https://github.com/django/django/blob/master/django/contrib/auth/urls.py?

**Comment by dicato** [comment] 2016-03-28 16:51
Good question! I suspect the best historical justification comes from the FAQ:

https://django-registration-redux.readthedocs.org/en/latest/faq.html#configuration

> I don’t want to write my own URLconf because I don’t want to write patterns for all the auth views!

>You’re in luck, then; django-registration-redux provides a URLconf which only contains the patterns for the auth views, and which you can include in your own URLconf anywhere you’d like; it lives at registration.auth_urls.

> I don’t like the names you’ve given to the URL patterns!

> In that case, you should feel free to set up your own URLconf which uses the names you want.

If either of you have a clearer implementation and documentation please open a pull request!

**Comment by dicato** [comment] 2016-06-01 16:23
@lydiagu and @bmsleight is there any work that needs to get done to address this issue?

**Comment by tclancy** [comment] 2016-06-09 19:17
For 1.9 I needed to use @bmsleight's solution above to get this working. I see the historical justification but I'd say the Principle of Least Surprise would be to have them work out of the box with Django's url names. The problem for me as a dev is that I forget to test things like resetting my password so these don't blow up until someone else tries to use them and even then the error message doesn't point directly to a solution. The `default/urls.py` file already does some switching based on settings. If there are worries about breaking with tradition, exposing an additional setting would be a possible solution.

**Comment by dicato** [comment] 2016-06-09 19:22
@tclancy I agree! From my perspective this is just waiting on someone to open a pull request with a solution. If you are interested, I'm happy to help review.

**Comment by maciej-kisiel** [comment] 2016-10-12 17:45
Wouldn't it be a better idea to just add a modified `password_reset_email.html` containing a correct name to reverse? As it was done for example with `login.html`?

**Comment by maciej-kisiel** [comment] 2016-10-12 18:19
It seems that putting `registration` over `django.contrib.admin` in `INSTALLED_APPS` solves this issue because templates connected to password resetting are in this app.

**Comment by jayache80** [comment] 2016-10-14 10:28
@maciej-kisiel Thanks, this helped me out.

**Closed** 2017-10-05 15:51 UTC
Labels: help wanted

**Comment by dE1l** [comment] 2018-02-27 08:59
I'm clone this repository now, 
run this test_app, 
go to reset password and this issue with "Reverse for 'password_reset_confirm'" was reproduced for me.

Then i changed settings.py to:
 INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'registration',
    'django.contrib.admin',
    'test_app',
)

And it fixed this problem.
Please, update you GIT !

Python 3.6
Django 2.0.2
