### ISSUE TITLE
redirect if user is logged in

### ISSUE THREAD

**Issue by elnappo** [macropin/django-registration#21] opened 2015-01-02 12:18 UTC
It would be nice if a logged in user who visits the registration views gets redirected to the site root or maybe a configurable site.

**Comment by LennyLip** [comment] 2015-03-14 07:52
Here is good decorator for logout_requered http://stackoverflow.com/a/5797020/1271271

**Comment by dicato** [comment] 2015-09-18 20:18
#96 is a duplicate of this. Given there is more conversation in #96 than this issue, I'm closing this issue.

**Closed by dicato** 2015-09-18 20:18 UTC
Labels: enhancement
