### ISSUE TITLE
Add support for Django 1.11

### ISSUE THREAD

**Issue by nagracks** [macropin/django-registration#252] opened 2017-04-17 17:44 UTC
If I include urls with namespace
```
    url(r'^accounts/', include('registration.backends.simple.urls', namespace='registration')),
```
And use it like this in template
```
<li><a href="{% url 'registration:auth_login' %}">Login</a></li>
```

then it is not working in latest Django.

**Comment by dicato** [comment] 2017-04-17 19:09
What do you mean by not working? Is there an exception being thrown?

**Comment by nagracks** [comment] 2017-04-18 02:29
Yes this exception
```
django.urls.exceptions.NoReverseMatch: Reverse for 'auth_password_reset_done' not found. 'auth_password_reset_done' is not a valid view function or pattern name.
```

**Comment by joshblum** [comment] 2017-04-25 15:38
@nagracks my guess would be that it's because the `auth_urls` are not included with the namespace: https://github.com/macropin/django-registration/blob/master/registration/backends/default/urls.py#L61 can you confirm this is the issue?

**Comment by timgraham** [comment] 2017-04-25 15:44
I couldn't reproduce this crash.

**Comment by fchevitarese** [comment] 2017-05-11 03:15
I'm having the same issue. 
I've updated my project to Django 1.10.5, and now, /accounts/login or other any related url does not work and throw this error: 

```django.urls.exceptions.NoReverseMatch
NoReverseMatch: Reverse for 'django.contrib.auth.views.login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []```

Any ideas ?

**Comment by timgraham** [comment] 2017-05-11 11:51
If you upgraded from 1.9 or earlier it might be related to this item in the 1.10 release notes: "The ability to reverse() URLs using a dotted Python path is removed." Does your URL pattern you are trying to reverse have a name?

**Comment by fchevitarese** [comment] 2017-05-11 11:56
They are like this: 
```
    from django.contrib.auth.views import login, logout
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^login/$', login, name='account_login'),
    url(r'^logout/$', logout, name='account_logout'),

**Comment by timgraham** [comment] 2017-05-11 11:57
It looks like you need to give `login` a name of `'django.contrib.auth.views.login'`.

**Comment by fchevitarese** [comment] 2017-05-11 12:00
It worked for login view, but registration urls are not found yet.

**Comment by timgraham** [comment] 2017-05-25 17:35
One more thing that could be done when closing this is to add 1.11 to the "django-registration (redux) now with Django 1.8/1.9/1.10" tag at the top of https://github.com/macropin/django-registration.

**Comment by joshblum** [comment] 2017-05-25 18:38
@timgraham agreed, only @macropin can change that currently so I'll let him edit and close this issue out.

**Comment by joshblum** [comment] 2017-09-13 14:40
@macropin can you update the tagline to close this issue?

**Comment by fchevitarese** [comment] 2017-09-13 15:10
I'm not sure how to do this. Can you help me?

Em 13/09/2017 11:40, "Joshua Blum" <notifications@github.com> escreveu:

@macropin <https://github.com/macropin> can you update the tagline to close
this issue?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/macropin/django-registration/issues/252#issuecomment-329189360>,
or mute the thread

**Comment by joshblum** [comment] 2017-09-13 18:15
@fchevitarese only @macropin can update the tagline as the repository owner. Thanks for reaching out though!

**Comment by timgraham** [comment] 2017-09-25 19:19
The tagline no longer includes the Django version so I think this can be closed.

**Closed** 2017-10-02 16:34 UTC
