### ISSUE TITLE
User model loaded before models are ready in registration/users.py:7

### ISSUE THREAD

**Issue by ritave** [macropin/django-registration#63] opened 2015-05-22 08:57 UTC
We encountered this problem during our nightlies (log below), searching the internet it seems that we're not the only ones with the problem (see http://stackoverflow.com/a/27845576/4783965 for a probable fix). Having checked django-registration-redux code I'm confirming that the user model is still being loaded during import time which will not work during django installed app population.

Log output:
```
+ ./test.sh --with-coverage '--cover-package=oioioi' --cover-html '--cover-html-dir=coverage' '--html-file=test_report/new_index.html'
Traceback (most recent call last):
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/share/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django_nose/__init__.py", line 4, in <module>
    from django_nose.runner import *
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django_nose/runner.py", line 262, in <module>
    class BaseRunner(DiscoverRunner):
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django_nose/runner.py", line 264, in BaseRunner
    options = _get_options()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django_nose/runner.py", line 123, in _get_options
    config.plugins.addPlugins(list(_get_plugins_from_settings()))
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django_nose/runner.py", line 103, in _get_plugins_from_settings
    mod = import_module(p_mod)
  File "/usr/share/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/src/oioioi/base/tests/__init__.py", line 49, in <module>
    from oioioi.base.middleware import UserInfoInErrorMessage
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/src/oioioi/base/middleware.py", line 14, in <module>
    from oioioi.base.views import has_valid_username
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/src/oioioi/base/views.py", line 21, in <module>
    from oioioi.base.forms import UserForm
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/src/oioioi/base/forms.py", line 8, in <module>
    from registration.forms import RegistrationForm
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/registration/forms.py", line 19, in <module>
    User = UserModel()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/registration/users.py", line 7, in UserModel
    return get_user_model()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 137, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/users/sio2devel/.hudson/jobs/oioioi-nightly-unittests/workspace/nightly-virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by macropin** [comment] 2015-05-28 09:43
Can you please submit a simple case that reproduces the issue. A fix and test case would be nice too ;)

**Comment by HiddenClever** [comment] 2015-06-03 15:12
I've had this issue too but it's in a project so complicated I wouldn't be able to extract a broken example easily. Even without an example though as a rule of thumb the User model should never be instantiated at import and this has been the case since custom user models were implemented. The following example allows backwards compatibility (originally taken from django-cms before they dropped support for older versions of Django) and allows you to use get_user_model() throughout:

    if django.VERSION >= (1, 5):
        from django.contrib.auth import get_user_model
    else:
        from django.contrib.auth.models import User
        User.USERNAME_FIELD = 'username'
        get_user_model = lambda: User

forms.py:

    class RegistrationFormUniqueEmail(RegistrationForm):
        ...
        def clean_email(self):
            ...
            if get_user_model().objects.filter(email__iexact=self.cleaned_data['email']):
                raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
            return self.cleaned_data['email']

**Comment by dicato** [comment] 2016-01-15 01:55
Fixed by https://github.com/macropin/django-registration/commit/e09500507742c781b7f77335a5db93e51693a3d6

**Closed by dicato** 2016-01-15 01:55 UTC
